
// ImageNet 1000 classes - Complete list for real classification
export const IMAGENET_CLASSES = [
  "tench", "goldfish", "great white shark", "tiger shark", "hammerhead shark",
  "electric ray", "stingray", "rooster", "hen", "ostrich",
  "brambling", "goldfinch", "house finch", "junco", "indigo bunting",
  "robin", "bulbul", "jay", "magpie", "chickadee",
  "water ouzel", "kite", "bald eagle", "vulture", "great grey owl",
  "fire salamander", "smooth newt", "newt", "spotted salamander", "axolotl",
  "bullfrog", "tree frog", "tailed frog", "loggerhead turtle", "leatherback turtle",
  "mud turtle", "terrapin", "box turtle", "banded gecko", "common iguana",
  "American chameleon", "whiptail lizard", "agama", "frilled lizard", "alligator lizard",
  "Gila monster", "green lizard", "African chameleon", "Komodo dragon", "African crocodile",
  "American alligator", "triceratops", "thunder snake", "ringneck snake", "hognose snake",
  "green snake", "king snake", "garter snake", "water snake", "vine snake",
  "night snake", "boa constrictor", "rock python", "Indian cobra", "green mamba",
  "sea snake", "horned viper", "diamondback rattlesnake", "sidewinder", "trilobite",
  "harvestman", "scorpion", "black and gold garden spider", "barn spider", "garden spider",
  "black widow", "tarantula", "wolf spider", "tick", "centipede",
  "black grouse", "ptarmigan", "ruffed grouse", "prairie chicken", "peacock",
  "quail", "partridge", "African grey parrot", "macaw", "sulphur-crested cockatoo",
  "lorikeet", "coucal", "bee eater", "hornbill", "hummingbird",
  "jacamar", "toucan", "drake", "red-breasted merganser", "goose",
  "black swan", "tusker", "echidna", "platypus", "wallaby",
  "koala", "wombat", "jellyfish", "sea anemone", "brain coral",
  "flatworm", "nematode", "conch", "snail", "slug",
  "sea slug", "chiton", "chambered nautilus", "Dungeness crab", "rock crab",
  "fiddler crab", "king crab", "American lobster", "spiny lobster", "crayfish",
  "hermit crab", "isopod", "white stork", "black stork", "spoonbill",
  "flamingo", "little blue heron", "American egret", "bittern", "crane",
  "limpkin", "European gallinule", "American coot", "bustard", "ruddy turnstone",
  "red-backed sandpiper", "redshank", "dowitcher", "oystercatcher", "pelican",
  "king penguin", "albatross", "grey whale", "killer whale", "dugong",
  "sea lion", "Chihuahua", "Japanese Chin", "Maltese", "Pekingese",
  "Shih Tzu", "Blenheim spaniel", "papillon", "toy terrier", "Rhodesian ridgeback",
  "Afghan hound", "basset hound", "beagle", "bloodhound", "bluetick coonhound",
  "black and tan coonhound", "Walker hound", "English foxhound", "redbone coonhound", "borzoi",
  "Irish wolfhound", "Italian greyhound", "whippet", "Ibizan hound", "Norwegian elkhound",
  "otterhound", "Saluki", "Scottish deerhound", "Weimaraner", "Staffordshire bull terrier",
  "American Staffordshire terrier", "Bedlington terrier", "Border terrier", "Kerry blue terrier", "Irish terrier",
  "Norfolk terrier", "Norwich terrier", "Yorkshire terrier", "wire fox terrier", "Lakeland terrier",
  "Sealyham terrier", "Airedale terrier", "cairn terrier", "Australian terrier", "Dandie Dinmont terrier",
  "Boston terrier", "miniature schnauzer", "giant schnauzer", "standard schnauzer", "Scotch terrier",
  "Tibetan terrier", "silky terrier", "soft-coated wheaten terrier", "West Highland white terrier", "Lhasa Apso",
  "flat-coated retriever", "curly-coated retriever", "golden retriever", "Labrador retriever", "Chesapeake Bay retriever",
  "German short-haired pointer", "vizsla", "English setter", "Irish setter", "Gordon setter",
  "Brittany", "clumber spaniel", "English springer spaniel", "Welsh springer spaniel", "cocker spaniel",
  "Sussex spaniel", "Irish water spaniel", "kuvasz", "schipperke", "groenendael",
  "malinois", "briard", "Australian kelpie", "komondor", "Old English sheepdog",
  "Shetland sheepdog", "collie", "Border collie", "Bouvier des Flandres", "Rottweiler",
  "German shepherd dog", "Doberman pinscher", "miniature pinscher", "Greater Swiss Mountain dog", "Bernese mountain dog",
  "Appenzeller Sennenhund", "Entlebucher Sennenhund", "boxer", "Bullmastiff", "Tibetan mastiff",
  "French bulldog", "Great Dane", "St. Bernard", "husky", "Alaskan Malamute",
  "Siberian husky", "dalmatian", "affenpinscher", "basenji", "pug",
  "Leonberger", "Newfoundland", "Great Pyrenees", "Samoyed", "Pomeranian",
  "chow chow", "keeshond", "brussels griffon", "Pembroke Welsh corgi", "Cardigan Welsh corgi",
  "toy poodle", "miniature poodle", "standard poodle", "Mexican hairless", "timber wolf",
  "white wolf", "red wolf", "coyote", "dingo", "dhole",
  "African wild dog", "hyena", "red fox", "kit fox", "Arctic fox",
  "grey fox", "tabby cat", "tiger cat", "Persian cat", "Siamese cat",
  "Egyptian Mau", "cougar", "lynx", "leopard", "snow leopard",
  "jaguar", "lion", "tiger", "cheetah", "brown bear",
  "American black bear", "ice bear", "sloth bear", "mongoose", "meerkat",
  "tiger beetle", "ladybug", "ground beetle", "longhorn beetle", "leaf beetle",
  "dung beetle", "rhinoceros beetle", "weevil", "fly", "bee",
  "ant", "grasshopper", "cricket", "walking stick", "cockroach",
  "mantis", "cicada", "leafhopper", "lacewing", "dragonfly",
  "damselfly", "admiral", "ringlet", "monarch butterfly", "cabbage butterfly",
  "sulphur butterfly", "lycaenid butterfly", "starfish", "sea urchin", "sea cucumber",
  "wood rabbit", "hare", "Angora rabbit", "hamster", "porcupine",
  "fox squirrel", "marmot", "beaver", "guinea pig", "common sorrel",
  "zebra", "pig", "wild boar", "warthog", "hippopotamus",
  "ox", "water buffalo", "bison", "ram", "bighorn sheep",
  "Alpine ibex", "hartebeest", "impala", "gazelle", "Arabian camel",
  "llama", "weasel", "mink", "polecat", "black-footed ferret",
  "otter", "skunk", "badger", "armadillo", "three-toed sloth",
  "orangutan", "gorilla", "chimpanzee", "gibbon", "siamang",
  "guenon", "patas monkey", "baboon", "macaque", "langur",
  "colobus monkey", "proboscis monkey", "marmoset", "capuchin", "howler monkey",
  "titi monkey", "spider monkey", "squirrel monkey", "Madagascar cat", "indri",
  "Indian elephant", "African bush elephant", "red panda", "giant panda", "barracouta",
  "eel", "coho salmon", "rock beauty", "anemone fish", "sturgeon",
  "gar", "lionfish", "pufferfish", "abacus", "abaya",
  "academic gown", "accordion", "acoustic guitar", "aircraft carrier", "airliner",
  "airship", "altar", "ambulance", "amphibian", "analog clock",
  "apiary", "apron", "ashcan", "assault rifle", "backpack",
  "bakery", "balance beam", "balloon", "ballpoint pen", "Band-Aid",
  "banjo", "bannister", "barbell", "barber chair", "barbershop",
  "barn", "barometer", "barrel", "wheelbarrow", "baseball",
  "basketball", "bassinet", "bassoon", "bathing cap", "bath towel",
  "bathtub", "station wagon", "beacon", "beaker", "bearskin",
  "beer bottle", "beer glass", "bell tower", "baby bib", "tandem bicycle",
  "bikini", "ring binder", "binoculars", "birdhouse", "boathouse",
  "bobsleigh", "bolo tie", "poke bonnet", "bookcase", "bookstore",
  "bottle cap", "hunting bow", "bow tie", "brass memorial tablet", "bra",
  "breakwater", "breastplate", "broom", "bucket", "buckle",
  "bulletproof vest", "high-speed train", "butcher shop", "taxicab", "cauldron",
  "candle", "cannon", "canoe", "can opener", "cardigan",
  "car mirror", "carousel", "tool kit", "cardboard box", "car wheel",
  "automated teller machine", "cassette", "cassette player", "castle", "catamaran",
  "CD player", "cello", "mobile phone", "chain", "chain-link fence",
  "chain mail", "chainsaw", "storage chest", "chiffonier", "bell tower",
  "china cabinet", "Christmas stocking", "church", "movie theater", "cleaver",
  "cliff dwelling", "cloak", "clogs", "cocktail shaker", "coffee mug",
  "coffeemaker", "spiral or coil", "combination lock", "computer keyboard", "candy store",
  "container ship", "convertible", "corkscrew", "cornet", "cowboy boot",
  "cowboy hat", "cradle", "construction crane", "crash helmet", "crate",
  "infant bed", "Crock Pot", "croquet ball", "crutch", "cuirass",
  "dam", "desk", "desktop computer", "rotary dial telephone", "diaper",
  "digital clock", "digital watch", "dining table", "dishrag", "dishwasher",
  "disc brake", "dock", "dog sled", "dome", "doormat",
  "drilling rig", "drum", "drumstick", "dumbbell", "Dutch oven",
  "electric fan", "electric guitar", "electric locomotive", "entertainment center", "envelope",
  "espresso machine", "face powder", "feather boa", "filing cabinet", "fireboat",
  "fire truck", "fire screen", "flagpole", "flute", "folding chair",
  "football helmet", "forklift", "fountain", "fountain pen", "four-poster bed",
  "freight car", "French horn", "frying pan", "fur coat", "garbage truck",
  "gas mask", "gas pump", "goblet", "go-kart", "golf ball",
  "golf cart", "gondola", "gong", "gown", "grand piano",
  "greenhouse", "radiator grille", "grocery store", "guillotine", "hair clip",
  "hair spray", "half-track", "hammer", "hamper", "hair dryer",
  "hand-held computer", "handkerchief", "hard disk drive", "harmonica", "harp",
  "combine harvester", "hatchet", "holster", "home theater", "honeycomb",
  "hook", "hoop skirt", "gymnastic horizontal bar", "horse-drawn vehicle", "hourglass",
  "iPod", "clothes iron", "carved pumpkin", "jeans", "jeep",
  "T-shirt", "jigsaw puzzle", "rickshaw", "joystick", "kimono",
  "knee pad", "knot", "lab coat", "ladle", "lampshade",
  "laptop computer", "lawn mower", "lens cap", "letter opener", "library",
  "lifeboat", "lighter", "limousine", "ocean liner", "lipstick",
  "slip-on shoe", "lotion", "music speaker", "loupe magnifying glass", "sawmill",
  "magnetic compass", "messenger bag", "mailbox", "maillot", "maillot tank suit",
  "manhole cover", "maraca", "marimba", "mask", "matchstick",
  "maypole", "maze", "measuring cup", "medicine chest", "megalith",
  "microphone", "microwave oven", "military uniform", "milk can", "minibus",
  "miniskirt", "minivan", "missile", "mitten", "mixing bowl",
  "mobile home", "Ford Model T", "modem", "monastery", "monitor",
  "moped", "mortar and pestle", "graduation cap", "mosque", "mosquito net",
  "vespa", "mountain bike", "tent", "computer mouse", "mousetrap",
  "moving van", "muzzle", "metal nail", "neck brace", "necklace",
  "baby pacifier", "notebook computer", "obelisk", "oboe", "ocarina",
  "odometer", "oil filter", "pipe organ", "oscilloscope", "overskirt",
  "bullock cart", "oxygen mask", "product packet / packaging", "paddle", "paddle wheel",
  "padlock", "paintbrush", "pajamas", "palace", "pan flute",
  "paper towel", "parachute", "parallel bars", "park bench", "parking meter",
  "railroad car", "patio", "payphone", "pedestal", "pencil case",
  "pencil sharpener", "perfume", "Petri dish", "photocopier", "plectrum",
  "Pickelhaube", "picket fence", "pickup truck", "pier", "piggy bank",
  "pill bottle", "pillow", "ping-pong ball", "pinwheel", "pirate ship",
  "drink pitcher", "block plane", "planetarium", "plastic bag", "plate rack",
  "farm plow", "plunger", "Polaroid camera", "pole", "police van",
  "poncho", "pool table", "soda bottle", "plant pot", "potter's wheel",
  "power drill", "prayer rug", "printer", "prison", "missile",
  "projector", "hockey puck", "punching bag", "purse", "quill",
  "quilt", "race car", "racket", "radiator", "radio",
  "radio telescope", "rain barrel", "recreational vehicle", "fishing casting reel", "reflex camera",
  "refrigerator", "remote control", "restaurant", "revolver", "rifle",
  "rocking chair", "rotisserie", "eraser", "rugby ball", "ruler measuring stick",
  "sneaker", "safe", "safety pin", "salt shaker", "sandal",
  "sarong", "saxophone", "scabbard", "weighing scale", "school bus",
  "schooner", "scoreboard", "CRT monitor", "screw", "screwdriver",
  "seat belt", "sewing machine", "shield", "shoe store", "shoji screen / room divider",
  "shopping basket", "shopping cart", "shovel", "shower cap", "shower curtain",
  "ski", "balaclava ski mask", "sleeping bag", "slide rule", "sliding door",
  "slot machine", "snorkel", "snowmobile", "snowplow", "soap dispenser",
  "soccer ball", "sock", "solar thermal collector", "sombrero", "soup bowl",
  "keyboard space bar", "space heater", "space shuttle", "spatula", "motorboat",
  "spider web", "spindle", "sports car", "spotlight", "stage",
  "steam locomotive", "through arch bridge", "steel drum", "stethoscope", "scarf",
  "stone wall", "stopwatch", "stove", "strainer", "tram",
  "stretcher", "couch", "stupa", "submarine", "suit",
  "sundial", "sunglasses", "sunglasses", "sunscreen", "suspension bridge",
  "mop", "sweatshirt", "swim trunks / shorts", "swing", "electrical switch",
  "syringe", "table lamp", "tank", "tape player", "teapot",
  "teddy bear", "television", "tennis ball", "thatched roof", "front curtain",
  "thimble", "threshing machine", "throne", "tile roof", "toaster",
  "tobacco shop", "toilet seat", "torch", "totem pole", "tow truck",
  "toy store", "tractor", "semi-trailer truck", "tray", "trench coat",
  "tricycle", "trimaran", "tripod", "triumphal arch", "trolleybus",
  "trombone", "hot tub", "turnstile", "typewriter keyboard", "umbrella",
  "unicycle", "upright piano", "vacuum cleaner", "vase", "monastery",
  "vestment", "viaduct", "violin", "volleyball", "waffle iron",
  "wall clock", "wallet", "wardrobe", "military aircraft", "sink",
  "washing machine", "water bottle", "water jug", "water tower", "whiskey jug",
  "whistle", "hair wig", "window screen", "window shade", "Windsor tie",
  "wine bottle", "airplane wing", "wok", "wooden spoon", "wool",
  "split-rail fence", "shipwreck", "sailboat", "yurt", "website",
  "comic book", "crossword", "traffic or street sign", "traffic light", "dust jacket",
  "menu", "plate", "guacamole", "consomme", "hot pot",
  "trifle", "ice cream", "popsicle", "baguette", "bagel",
  "pretzel", "cheeseburger", "hot dog", "mashed potatoes", "cabbage",
  "broccoli", "cauliflower", "zucchini", "spaghetti squash", "acorn squash",
  "butternut squash", "cucumber", "artichoke", "bell pepper", "cardoon",
  "mushroom", "Granny Smith apple", "strawberry", "orange", "lemon",
  "fig", "pineapple", "banana", "jackfruit", "cherimoya",
  "pomegranate", "hay", "carbonara", "chocolate syrup", "dough",
  "meatloaf", "pizza", "pot pie", "burrito", "red wine",
  "espresso", "tea cup", "eggnog", "mountain", "bubble",
  "cliff", "coral reef", "geyser", "lakeshore", "promontory",
  "sandbar", "beach", "valley", "volcano", "baseball player",
  "bridegroom", "scuba diver", "rapeseed", "daisy", "yellow lady's slipper",
  "corn", "acorn", "rose hip", "horse chestnut seed", "coral fungus",
  "agaric", "gyromitra", "stinkhorn mushroom", "earth star", "hen of the woods mushroom",
  "bolete", "corn cob", "toilet paper"
]

// Simplified superclass mapping for ImageNet classes
export function getImageNetSuperclass(classIndex: number): string {
  // Animals
  if (classIndex >= 0 && classIndex <= 389) {
    if (classIndex <= 149) return "fish and aquatic animals"
    if (classIndex <= 199) return "birds"
    if (classIndex <= 269) return "mammals"
    if (classIndex <= 319) return "insects and arthropods"
    return "reptiles and amphibians"
  }
  // Objects and vehicles
  if (classIndex >= 390 && classIndex <= 899) {
    if (classIndex <= 599) return "vehicles and transportation"
    if (classIndex <= 699) return "household items"
    if (classIndex <= 799) return "tools and equipment"
    return "clothing and accessories"
  }
  // Food and natural objects
  if (classIndex >= 900) {
    if (classIndex <= 969) return "food and beverages"
    return "natural objects and plants"
  }
  
  return "miscellaneous"
}
